#!/bin/bash

if [ $# -lt 1 ]; then 
    echo usage: FILE [region] [group] [instance] [owner]
    exit 1
fi

FILE=$(readlink -f $1)
REGION=${2:-eastus}
GROUP=${3:-onefuzz-bmc}
INSTANCE=${4:-onefuzz-bmc}
OWNER=${5:-bcaswell}

if [ ! -f ${FILE} ]; then 
    echo no such file: ${FILE}
    exit 1
fi

cd $(dirname "$(readlink -f "$0")")
eval $(direnv export bash)

./d1 $FILE $REGION $GROUP $INSTANCE $OWNER
./new-build.py
$ONEFUZZ_SRC_ROOT/src/cli/examples/integration-test.py test $ONEFUZZ_SRC_ROOT/../built-samples/ --region eastus2 --user_pools linux=linux windows=windows
